describe('E2E Test - Payments', ()=>{
    it('Should login into application', () => {
        browser.url('http://zero.webappsecurity.com/')
        browser.maximizeWindow()
        let signinBtn = $('#signin_button')
        signinBtn.waitForExist()
        signinBtn.click()
        let signinForm = $('#login_form')
        signinForm.waitForExist()
        let user= $('#user_login')
        let password= $('#user_password')
        let submitBtn = $('input.btn-primary')
        user.setValue('username')
        password.setValue('password')
        submitBtn.click()
        let navBar = $('ul.nav-tabs')
        navBar.waitForExist()
        expect(navBar).toBeVisibleInViewport()
    })
    it('Should make payments', ()=>{
        let paybillsMenu = $('=Pay Bills')
        paybillsMenu.waitForExist()
        paybillsMenu.click()
        let payee = $('#sp_payee')
        let account = $('#sp_account')
        let amount = $('#sp_amount')
        let date = $('#sp_date')
        let description = $('#sp_description')
        let payButton = $('#pay_saved_payees')
        payee.waitForExist()
        payee.selectByAttribute('value','apple')
        account.selectByVisibleText('Savings')
        amount.setValue('300')
        date.setValue('2020-04-08')
        description.setValue('Test values')
        payButton.click()
        let message = $('#alert_container')
        console.log(message.getText())
        expect(message).toHaveText('×\nThe payment was successfully submitted.')
    })
})