// import App from '../pages_objects/App'
const app = require('../pages_objects/App')

describe('E2E Feedback tests', ()=>{
    it.only('Should load feedback form', ()=>{
        app.openHomepage()
        browser.maximizeWindow()
        let feedbackMenu = $('#feedback')
        feedbackMenu.waitForExist()
        feedbackMenu.click()
        let form = $('form')
        form.waitForExist()
        expect(form).toBeVisibleInViewport()
    })
    it('Should enter data in form and clear form', ()=>{
        let name = $('#name')
        let email = $('#email')
        let subject = $('#subject')
        let comment = $('#comment')
        let clearBtn = $(`input[type="reset"]`)
        name.setValue('test')
        email.setValue('test@test.com')
        subject.setValue('WebdriverIO')
        comment.setValue('This is a comment test!!!!')
        clearBtn.click()
    })
    it('Should submit feedback form', ()=>{
        let name = $('#name')
        let email = $('#email')
        let subject = $('#subject')
        let comment = $('#comment')
        let sendMsgBtn = $('.btn-signin')
        name.setValue('test')
        email.setValue('test@test.com')
        subject.setValue('WebdriverIO')
        comment.setValue('This is a comment test!!!!')
        sendMsgBtn.click()
        let result = $('#feedback-title')
        result.waitForExist()
        expect(result).toHaveText('Feedback')
    })
})