describe('E2E Test - Help Tests', ()=>{
    it('Should login into application', () => {
        browser.url('http://zero.webappsecurity.com/')
        browser.maximizeWindow()
        let signinBtn = $('#signin_button')
        signinBtn.waitForExist()
        signinBtn.click()
        let signinForm = $('#login_form')
        signinForm.waitForExist()
        let user= $('#user_login')
        let password= $('#user_password')
        let submitBtn = $('input.btn-primary')
        user.setValue('username')
        password.setValue('password')
        submitBtn.click()
        let navBar = $('ul.nav-tabs')
        navBar.waitForExist()
        expect(navBar).toBeVisibleInViewport()
    })
    it('Should load help content', ()=>{
        let iconCog = $('.icon-cog')
        iconCog.waitForExist()
        iconCog.click()
        let helpLink = $('#help_link')
        helpLink.waitForExist()
        helpLink.click()
        let title = $('.span8 >h3')
        expect(title).toHaveText('How do I log into my account?')
        let secondLink = $('*=transfer funds?')
        secondLink.click()
        expect(title).toHaveText('How do I transfer funds?')
        let thirdLink = $('*=do I pay bills?')
        thirdLink.click()
        expect(title).toHaveText('How do I pay bills?')
    })
})