describe('E2E Test - Filter transactions', ()=>{
    it('Should login into application', () => {
        browser.url('http://zero.webappsecurity.com/')
        browser.maximizeWindow()
        let signinBtn = $('#signin_button')
        signinBtn.waitForExist()
        signinBtn.click()
        let signinForm = $('#login_form')
        signinForm.waitForExist()
        let user= $('#user_login')
        let password= $('#user_password')
        let submitBtn = $('input.btn-primary')
        user.setValue('username')
        password.setValue('password')
        submitBtn.click()
        let navBar = $('ul.nav-tabs')
        navBar.waitForExist()
        expect(navBar).toBeVisibleInViewport()
    })
    it('Should filter and find no transactions', ()=>{
        let acccountActivityMenu = $('=Account Activity')
        acccountActivityMenu.waitForExist()
        acccountActivityMenu.click()
        let findTransactionsTab = $('=Find Transactions')
        findTransactionsTab.waitForExist()
        findTransactionsTab.click()
        let description = $('#aa_description')
        let findButton = $('button.btn-primary')
        description.setValue('test')
        findButton.click()
        let div = $('#filtered_transactions_for_account')
        div.waitForExist()
        let message = $('div.well')
        expect(message).toHaveText('No results.')
    })
    it('Should filter and find a transactions', ()=>{
        let acccountActivityMenu = $('=Account Activity')
        acccountActivityMenu.waitForExist()
        acccountActivityMenu.click()
        let findTransactionsTab = $('=Find Transactions')
        findTransactionsTab.waitForExist()
        findTransactionsTab.click()
        let description = $('#aa_description')
        let fromDate = $('#aa_fromDate')
        let toDate = $('#aa_toDate')
        let fromAmount = $('#aa_fromAmount')
        let toAmount = $('#aa_toAmount')
        let typeSelect = $('#aa_type')
        let findButton = $(`button[type="submit"]`)
        description.setValue('ONLINE')
        fromDate.setValue('2012-05-06')
        toDate.setValue('2020-04-01')
        // fromAmount.setValue('1')
        // toAmount.setValue('1000')
        typeSelect.selectByAttribute('value','DEPOSIT')
        findButton.click()
        // let div = $('#filtered_transactions_for_account')
        // div.waitForExist()
        // let resultsTable = $(`#filtered_transactions_for_account > table:nth-child(1)`)
        // expect(resultsTable).toBeDisplayed()
        browser.pause(10000)
    })
})